services:
  bevfusion: 
    build:
      context: .
      dockerfile: ../docker/bevfusion/Dockerfile
    ipc: host
    stdin_open: true
    tty: true
    volumes:
      - /mnt/wato-drive/perception/nuScenes:/dataset
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]