services:
  mmdetection3d: 
    build:
      context: .
      dockerfile: ../docker/mmdetection3d/Dockerfile
    ipc: host
    stdin_open: true
    tty: true
    volumes:
      - ../:/Perception-Research
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]