carla:
  host: 'carla_server'
  port: 2000
  timeout: 10.0
  sync:
    fps: 30
    timeout: 10.0
  seed: 23
  traffic_manager_port: 8000
  townmap: "Town04"

output_dir: "_out"
max_frames: 10 # Number of frames to capture

weather:
  cloudiness: 0.0
  precipitation: 0.0
  precipitation_deposits: 0.0
  wind_intensity: 0.0
  sun_azimuth_angle: 0.0
  sun_altitude_angle: 10.0
  fog_density: 0.0
  fog_distance: 0.0
  wetness: 0.0

spawn_actors:
  - blueprint:
      name: "vehicle.*"
      attr: {role_name: "hero"}
    sensors:
    - blueprint:
        name: "sensor.camera.rgb"
        attr: {"image_size_x": "800", "image_size_y": "600"}
      transform:
        location: {x: -6.0, z: 1.5}
      attachment: "rigid"
    # - blueprint:
    #     name: "sensor.camera.depth"
    #     attr: {"image_size_x": "800", "image_size_y": "600"}
    #   transform:
    #     location: {x: -6.0, z: 1.5}
    #   attachment: "rigid"
    # - blueprint:
    #     name: "sensor.camera.instance_segmentation"
    #     attr: {"image_size_x": "800", "image_size_y": "600"}
    #   transform:
    #     location: {x: -6.0, z: 1.5}
    #   attachment: "rigid"
