carla:
  host: '127.0.0.1'
  port: 2000
  timeout: 5.0
  sync:
    fps: 30
    timeout: 2.0
  townmap: "Town10HD"
  traffic_manager_port: 8000

output_dir: "_out"
max_frames: 100

weather:
  cloudiness: 0.0
  precipitation: 0.0
  precipitation_deposits: 0.0
  wind_intensity: 0.0
  sun_azimuth_angle: 0.0
  sun_altitude_angle: 10.0
  fog_density: 0.0
  fog_distance: 0.0
  wetness: 0.0

spawn_actors:
  - blueprint: 
      name: "sensor.camera.instance_segmentation"
      attr: {"image_size_x": "800", "image_size_y": "600"}
      speed: 1.0
    transform:
      location: {x: -60.0, y: 1.0, z: 2.0} 
    destination_transform: 
      location: {x: 45.0, y: 1.0, z: 2.0} 
    sensor_motion:
      jitter_magnitude: {"x": 0.01, "y": 0.001, "z": 0.01}
  - blueprint: 
      name: "sensor.camera.rgb"
      attr: {"image_size_x": "800", "image_size_y": "600", "gamma": "2.2"}
      speed: 1.0
    transform:
      location: {x: -60.0, y: 1.0, z: 2.0} 
    destination_transform: 
      location: {x: 45.0, y: 1.0, z: 2.0}
    sensor_motion:
      jitter_magnitude: {"x": 0.01, "y": 0.001, "z": 0.01}
