carla:
  host: '127.0.0.1'
  port: 2000
  timeout: 5.0
  traffic_manager_port: 8000
  sync:
    fps: 10
    timeout: 2.0

output_dir: "_out"
max_frames: 1000

weather:
  cloudiness: 0.0
  precipitation: 0.0
  precipitation_deposits: 0.0
  wind_intensity: 0.0
  sun_azimuth_angle: 0.0
  sun_altitude_angle: 10.0
  fog_density: 0.0
  fog_distance: 0.0
  wetness: 0.0

spawn_actors:
  - blueprint: 
      name: "sensor.camera.instance_segmentation"
      attr: {"image_size_x": "800", "image_size_y": "600"}
    transform:
      location: {x: -6.0, z: 1.5} 
    attach_to: "hero"
  - blueprint: 
      name: "sensor.camera.rgb"
      attr: {"image_size_x": "800", "image_size_y": "600", "gamma": "2.2"}
    transform: 
      location: {x: -6.0, z: 1.5} 
    attachment: "rigid"
    attach_to: "hero"
